### ISSUE TITLE
no more lyrics available?

### ISSUE THREAD

**Issue by petevliet** [timrogers/rapgenius#22] opened 2015-06-09 23:08 UTC
now that you're working with the Genius API, are lines from songs no longer available? Gem is no longer retrieving lyrics for my app

**Comment by timrogers** [comment] 2015-06-10 14:59
May need some work to function with the new API. I can take a look later on today!

**Comment by alexbooker** [comment] 2015-06-14 17:58
Hm. Is it just me, or does the [API](https://docs.genius.com/) not expose lyrics any more? It seems like the only way to attain lyrics is to scrape their website or, patch the lyrics together based on referrants (but they are out of order). Any thoughts, @timrogers?

**Comment by kerwinkerwin** [comment] 2015-06-15 05:23
@timrogers @petevliet is an issue with the access token not being used properly, You need to do the following in you search - 
![screen shot 2015-06-15 at 5 22 24 pm](https://cloud.githubusercontent.com/assets/9330672/8153516/22f19128-1383-11e5-833a-9ab9a6951d7f.png)

**Comment by timrogers** [comment] 2015-06-15 19:07
@kerwinkerwin Thanks for that - now fixed in v1.1.1 :+1:

**Comment by timrogers** [comment] 2015-06-15 19:07
@alexbooker seems to be right - no more lyrics in the public API :(

**Closed by timrogers** 2015-06-15 19:07 UTC

**Comment by alexbooker** [comment] 2015-06-15 19:16
@timrogers  Then why does @kerwinkerwin's fix still apply o.o?

**Comment by timrogers** [comment] 2015-06-15 19:16
@alexbooker Shouldn't apply now - works for me without in the new gem version.

**Comment by alexbooker** [comment] 2015-06-15 19:39
I mean, if the API does not support lyrics, how does v1.1.1 resolve the issue?

**Comment by timrogers** [comment] 2015-06-15 20:08
This issue isn't resolved - I've just closed it as it's non-resolvable
given that the API no longer supports actually getting the lyrics. I'll
update the code when I get a chance to reflect that - sorry!

--

Tim Rogers
+44 (0)7969 288259
@timrogers

**Comment by alexbooker** [comment] 2015-06-15 20:20
I have been in touch with someone at Genius and he confirmed that the API does not support lyrics at this time. I asked him if it was a possibility and am waiting a response :+1: I'll let y'all know what he says.

**Comment by timrogers** [comment] 2015-06-15 20:21
I strongly suspect it's a licensing thing - which is a shame :(

**Comment by alexbooker** [comment] 2015-06-15 20:26
If that is true then indeed, it would be a shame. I guess we'll see. 

I wonder if they'll object to scraping their html?
